name: neobis_flutter_cooks_corner_rodion
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Style package
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.10
  flutter_gen: ^5.3.2
  flutter_svg: ^2.0.7
  
  # Navigation Components
  auto_route: ^7.8.4
  
    # DI (Get It)
  get_it: ^7.6.0
  injectable: ^2.1.2

  # BLoC + Provider
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  rxdart: ^0.27.7

  # Remote
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

  # Local DB
  flutter_secure_storage: ^4.2.1

  # Generated
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0

   # Localization
  slang: 3.29.0
  slang_flutter: 3.29.0
  flutter_localizations:
    sdk: flutter
  
  # Utils
  top_snackbar_flutter: ^3.1.0
  image_picker: ^1.0.7
  fpdart: ^1.1.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  build_runner:
  flutter_gen_runner:
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.1
  slang_build_runner: 3.29.0
  json_serializable: ^6.7.0

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
 
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/





